openapi: 3.0.0
info:
  version: 0.0-oas3
  title: cpuinfo
  description: >-
    A simple service to get cpuinfo as an example of using swagger-2.0
    specification and codegen
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
paths:
  /predict/{id}:
    get:
      tags:
        - PRED
      operationId: prediction.my_prediction
      description: returns price at date given
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: array
            items:
              type: number
            minItems: 1
          style: simple
          explode: true
        - in: query
          name: metadata
          schema:
            type: boolean
      responses:
        '200':
          description: 'bit price'
  /calc/{id1},{id2}:
    get:
      tags:
        - PRED
      operationId: calc.my_prediction
      description: returns buy or sell
      parameters:
        - in: path
          name: id1
          required: true
          schema:
            type: array
            items:
              type: number
            minItems: 1
          style: simple
          explode: true
        - in: path
          name: id2
          required: true
          schema:
            type: array
            items:
              type: number
            minItems: 1
          style: simple
          explode: true
        - in: query
          name: metadata
          schema:
            type: boolean
      responses:
        '200':
          description: 'buy/sell'
servers:
  - url: 'http://localhost:8080/engr-222'
components:
  schemas:
    CPU:
      type: object
      required:
        - model
      properties:
        model:
          type: string
    OS:
      type: object
      required:
        - model
      properties:
        model:
          type: string
    BIT:
      type: object
      required:
        - model
      properties:
        model:
          type: string
